### ISSUE TITLE
Sprung feedback

### ISSUE THREAD

**Issue by pbek** [guija/sprung#1]
I tested Sprung for you, it worked really well.
This is what came to mind:
- when clicking the settings menu entry in the context menu I only got a message from Windows 8.1 how I want to open a JSON file
- it would be nice to open other installed programs with Sprung
- it would be great to solve simple equations like `3+9*22`

**Comment by guija** [comment]
Thanks for your feedback!
What would you expect to happen when clicking the settings entry in the taskbar context menu?
Regarding the other to points: I like tools one job and that very well, therefore I first want to focus on the main functionality and then on others. But i think that for calculating as a user I would rather use the Window calc.exe and for launching apps the Windows Start Menu is excellent I think.

**Comment by pbek** [comment]
> settings

ideally I would expect a settings dialog to be opened :)
